[build]
  base = ""
  publish = "build"
  command = "yarn build"

[context.production.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "12.16.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
