const authTypes = {
  CLEAR_SESSION: 'CLEAR_SESSION',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SET_GUEST_LOCALE: 'SET_GUEST_LOCALE',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP: 'SIGN_UP',
  UPDATE_USER: 'UPDATE_USER',
};

export default {
  ...authTypes,
};
